#IMPORTO CONEXION
import Conexion as Cx
#IMPORTO MENU MAIN
import Menu_Main as Mm
#LLEVO EL ARCHIVO CONEXION A LA VARIABLE PARA LLAMARLA Y AGILIZAR FUNCIONALIDADES
conexion=Cx.conexion
#LO MISMO CON CURSOR QUE LO INTRODUZCO EN LA VARIABLE CURSOR
cursor=Cx.cursor
#MENU MAIN CON AMBAS VARIABLES
Mm.Menu(conexion,cursor)
